window.SHARK_PRODUCTS = [
  {
    "name": "PILOT Elite 18K",
    "brand": "PILOT",
    "category": "万年筆",
    "year": "1970年代",
    "condition": "A",
    "price": "5,800円",
    "status": "販売中",
    "image": "images/products/pilot-elite18k.jpg",
    "description": "コンパクトサイズの人気モデル。18Kペン先。",
    "sortDate": "2026-07-21"
  },
  {
    "name": "PARKER 45 Flighter",
    "brand": "PARKER",
    "category": "万年筆",
    "year": "1980年代",
    "condition": "A",
    "price": "8,800円",
    "status": "販売中",
    "image": "images/products/parker45.jpg",
    "description": "ステンレスボディの定番モデル。",
    "sortDate": "2026-07-22"
  },
  {
    "name": "PLATINUM #3776",
    "brand": "PLATINUM",
    "category": "万年筆",
    "year": "1990年代",
    "condition": "A",
    "price": "12,800円",
    "status": "販売中",
    "image": "images/products/3776.jpg",
    "description": "14Kペン先。人気の国産万年筆。",
    "sortDate": "2026-07-23"
  },
  {
    "name": "SAILOR Profit 21",
    "brand": "SAILOR",
    "category": "万年筆",
    "year": "2000年代",
    "condition": "A",
    "price": "18,000円",
    "status": "販売中",
    "image": "images/products/profit21.jpg",
    "description": "21Kペン先。滑らかな書き味。",
    "sortDate": "2026-07-24"
  },
  {
    "name": "Pelikan M200 Green",
    "brand": "Pelikan",
    "category": "万年筆",
    "year": "1990年代",
    "condition": "A",
    "price": "22,000円",
    "status": "販売中",
    "image": "images/products/m200.jpg",
    "description": "グリーンストライプの人気モデル。",
    "sortDate": "2026-07-25"
  },
  {
    "name": "LAMY 2000",
    "brand": "LAMY",
    "category": "万年筆",
    "year": "現行",
    "condition": "A",
    "price": "28,000円",
    "status": "販売中",
    "image": "images/products/lamy2000.jpg",
    "description": "バウハウスデザインの名作。",
    "sortDate": "2026-07-26"
  },
  {
    "name": "Waterman Carène",
    "brand": "Waterman",
    "category": "万年筆",
    "year": "現行",
    "condition": "A",
    "price": "35,000円",
    "status": "販売中",
    "image": "images/products/carene.jpg",
    "description": "美しい流線形デザイン。",
    "sortDate": "2026-07-27"
  },
  {
    "name": "Pelikan M400 Green Stripe",
    "brand": "Pelikan",
    "category": "万年筆",
    "year": "1980年代",
    "condition": "A",
    "price": "48,000円",
    "status": "販売中",
    "image": "images/products/m400.jpg",
    "description": "14Cペン先。人気の一品。",
    "sortDate": "2026-07-28"
  },
  {
    "name": "PARKER Duofold Centennial",
    "brand": "PARKER",
    "category": "万年筆",
    "year": "1990年代",
    "condition": "A",
    "price": "68,000円",
    "status": "販売中",
    "image": "images/products/duofold.jpg",
    "description": "英国を代表するフラッグシップモデル。",
    "sortDate": "2026-07-29"
  },
  {
    "name": "Montblanc Meisterstück 146",
    "brand": "Montblanc",
    "category": "万年筆",
    "year": "1980年代",
    "condition": "A",
    "price": "88,000円",
    "status": "販売中",
    "image": "images/products/146.jpg",
    "description": "14Cニブ搭載の人気モデル。",
    "sortDate": "2026-07-30"
  },
  {
    "name": "Montblanc Meisterstück 149",
    "brand": "Montblanc",
    "category": "万年筆",
    "year": "1970年代",
    "condition": "A",
    "price": "138,000円",
    "status": "販売中",
    "image": "images/products/149.jpg",
    "description": "18Cニブ搭載。大型フラッグシップ。",
    "sortDate": "2026-07-31"
  },
  {
    "name": "Pelikan Toledo M700",
    "brand": "Pelikan",
    "category": "万年筆",
    "year": "1990年代",
    "condition": "A",
    "price": "180,000円",
    "status": "販売中",
    "image": "images/products/toledo.jpg",
    "description": "銀装飾が美しい高級モデル。",
    "sortDate": "2026-08-01"
  },
  {
    "name": "Namiki Yukari Royale",
    "brand": "NAMIKI",
    "category": "万年筆",
    "year": "現行",
    "condition": "A",
    "price": "280,000円",
    "status": "販売中",
    "image": "images/products/yukari.jpg",
    "description": "蒔絵仕上げの高級モデル。",
    "sortDate": "2026-08-02"
  },
  {
    "name": "Montblanc Hemingway Limited Edition",
    "brand": "Montblanc",
    "category": "万年筆",
    "year": "1992年",
    "condition": "A",
    "price": "398,000円",
    "status": "販売中",
    "image": "images/products/hemingway.jpg",
    "description": "人気の作家シリーズ限定モデル。",
    "sortDate": "2026-08-03"
  },
  {
    "name": "Montblanc 149 Celluloid",
    "brand": "Montblanc",
    "category": "万年筆",
    "year": "1950年代",
    "condition": "A",
    "price": "498,000円",
    "status": "販売中",
    "image": "images/products/149-celluloid.jpg",
    "description": "希少なセルロイドモデル。",
    "sortDate": "2026-08-04"
  },
  {
    "name": "MONTBLANC 146",
    "brand": "MONTBLANC",
    "category": "万年筆",
    "year": "希少限定レア",
    "condition": "A",
    "price": "720,000円",
    "status": "販売中",
    "image": "images/products/146-4-1.jpg",
    "description": "大変貴重な万年筆です。商品の詳しい状態についてはお問い合わせください。",
    "featured": true,
    "new": true,
    "sortDate": "2026-08-05"
  }
];
